# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GXWToolKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'YYImage'
  pod 'YYImage/WebP'
  pod 'YYWebImage'
  # Pods for GXWToolKitDemo

end
